# Generated by Django 4.1.6 on 2023-02-11 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_wishlist_product_wishlistitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitems',
            name='wish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_items', to='accounts.wishlist'),
        ),
    ]
