# Generated by Django 4.1.6 on 2023-02-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_profile_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ip',
            field=models.GenericIPAddressField(auto_created=True, null=True),
        ),
    ]
