# Generated by Django 4.1.6 on 2023-02-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ip',
        ),
    ]
