# Generated by Django 4.1.7 on 2023-05-29 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_deliveredcartitems_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitems",
            name="cart",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cart_items",
                to="accounts.cart",
            ),
        ),
    ]
