# Generated by Django 4.1.7 on 2023-05-29 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_alter_deliveredcartitems_cart_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitems",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="accounts.cart",
            ),
        ),
    ]
