# Generated by Django 4.1.7 on 2023-05-29 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_alter_deliveredcartitems_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveredcartitems",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivered_cart_items",
                to="accounts.deliveredcart",
            ),
        ),
        migrations.AlterField(
            model_name="paidcartitems",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paid_cart_items",
                to="accounts.paidcart",
            ),
        ),
    ]
