# Generated by Django 4.1.6 on 2023-02-09 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_just_arrived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dress',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_dress', to='products.dresses'),
        ),
    ]
