# Generated by Django 4.1.6 on 2023-02-10 10:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_dress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('collection_image', models.ImageField(upload_to='collection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
