# Generated by Django 4.1.6 on 2023-02-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_collection_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
